version: '3'

env:

  TASK_X_MAP_VARIABLES: 1

  AGENT_BIN_DIR: cmd/agent
  AGENT_BIN_NAME: agent
  AGENT_BIN_PATH: "{{.AGENT_BIN_DIR}}/{{.AGENT_BIN_NAME}}"

  SERVER_BIN_DIR: cmd/server
  SERVER_BIN_NAME: server
  SERVER_BIN_PATH: "{{.SERVER_BIN_DIR}}/{{.SERVER_BIN_NAME}}"

tasks:

  build-server:
    cmds:
      - go build -v -o "{{.SERVER_BIN_PATH}}" "{{.SERVER_BIN_DIR}}/main.go"

  build-agent:
    cmds:
      - go build -v -o "{{.AGENT_BIN_PATH}}" "{{.AGENT_BIN_DIR}}/main.go"

  build:
    run: once
    deps: [ build-agent, build-server ]

  run-server:
    deps: [ build-server ]
    cmds:
      - "{{.SERVER_BIN_PATH}} {{.CLI_ARGS}}"

  run-agent:
    deps: [ build-agent ]
    cmds:
      - "{{.AGENT_BIN_PATH}} {{.CLI_ARGS}}"

  linter:
    run: once
    cmd: go vet -vettool=`which statictest` ./...

  unit-tests:
    deps: [ linter, build ]
    run: once
    vars:
      CACHED: '{{.CACHED | default "-count 1" }}'
    cmd: go test {{.CACHED}}  ./...

  bench-tests:
    deps: [ linter, build ]
    cmd: go test -bench=. ./...

  coverage-report:
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -func=coverage.out | grep total
      - go tool cover -html=coverage.out -o coverage.html
      - open coverage.html

  iter-1:
    deps: [ unit-tests ]
    cmds:
      - |
        metricstest -test.v -test.run=^TestIteration1$ \
          -binary-path={{.SERVER_BIN_PATH}}

  iter-2:
    deps: [ unit-tests, iter-1, ]
    cmds:
      - |
        metricstest -test.v -test.run=^TestIteration2[AB]*$ \
          -source-path=. \
          -agent-binary-path={{.AGENT_BIN_PATH}}

  iter-3:
    deps: [ unit-tests, iter-2, ]
    cmds:
      - |
        metricstest -test.v -test.run=^TestIteration3[AB]*$ \
          -source-path=. \
          -agent-binary-path={{.AGENT_BIN_PATH}} \
          -binary-path={{.SERVER_BIN_PATH}}

  iter-4:
    deps: [ unit-tests, iter-3, ]
    cmds:
      - |
        SERVER_PORT=$(random-practicum unused-port)
        ADDRESS="localhost:${SERVER_PORT}"
        TEMP_FILE=$(random-practicum tempfile)
        metricstest -test.v -test.run=^TestIteration4$ \
          -agent-binary-path={{.AGENT_BIN_PATH}} \
          -binary-path={{.SERVER_BIN_PATH}} \
          -server-port=$SERVER_PORT \
          -source-path=.

  iter-5:
    deps: [ unit-tests, iter-4, ]
    cmds:
      - |
        SERVER_PORT=$(random-practicum unused-port)
        ADDRESS="localhost:${SERVER_PORT}"
        TEMP_FILE=$(random-practicum tempfile)
        SERVER_PORT=$(random-practicum unused-port) metricstest -test.v -test.run=^TestIteration5$ \
          -agent-binary-path={{.AGENT_BIN_PATH}} \
          -binary-path={{.SERVER_BIN_PATH}} \
          -server-port=$SERVER_PORT \
          -source-path=.

  iter-6:
    deps: [ unit-tests, iter-5, ]
    cmds:
      - |
        SERVER_PORT=$(random-practicum unused-port)
        ADDRESS="localhost:${SERVER_PORT}"
        TEMP_FILE=$(random-practicum tempfile)
        metricstest -test.v -test.run=^TestIteration6$ \
          -agent-binary-path={{.AGENT_BIN_PATH}} \
          -binary-path={{.SERVER_BIN_PATH}} \
          -server-port=SERVER_PORT \
          -source-path=.

  iter-7:
    deps: [ unit-tests, iter-6, ]
    cmds:
      - |
        SERVER_PORT=$(random-practicum unused-port)
        ADDRESS="localhost:${SERVER_PORT}"
        TEMP_FILE=$(random-practicum tempfile)
        metricstest -test.v -test.run=^TestIteration7$ \
          -agent-binary-path={{.AGENT_BIN_PATH}} \
          -binary-path={{.SERVER_BIN_PATH}} \
          -server-port=$SERVER_PORT \
          -source-path=.

  iter-8:
    deps: [ unit-tests, iter-7, ]
    cmds:
      - |
        SERVER_PORT=$(random-practicum unused-port)
        ADDRESS="localhost:${SERVER_PORT}"
        TEMP_FILE=$(random-practicum tempfile)
        metricstest -test.v -test.run=^TestIteration8$ \
          -agent-binary-path={{.AGENT_BIN_PATH}} \
          -binary-path={{.SERVER_BIN_PATH}} \
          -server-port=$SERVER_PORT \
          -source-path=.

  iter-9:
    deps: [ unit-tests, iter-8, ]
    cmds:
      - |
        SERVER_PORT=$(random-practicum unused-port)
        ADDRESS="localhost:${SERVER_PORT}"
        TEMP_FILE=$(random-practicum tempfile)
        metricstest -test.v -test.run=^TestIteration9$ \
          -agent-binary-path={{.AGENT_BIN_PATH}} \
          -binary-path={{.SERVER_BIN_PATH}} \
          -file-storage-path=$TEMP_FILE \
          -server-port=$SERVER_PORT \
          -source-path=.

  iter-10:
    deps: [ unit-tests, iter-9, ]
    vars:
      DATABASE_DSN: postgres://postgres:password@localhost:5432/postgres
    preconditions:
      - test -n "$(lsof -i :5432)"

    cmds:
      - |
        SERVER_PORT=$(random-practicum unused-port)
        ADDRESS="localhost:${SERVER_PORT}"
        TEMP_FILE=$(random-practicum tempfile)
        metricstest -test.v -test.run=^TestIteration10[AB]$ \
          -agent-binary-path={{.AGENT_BIN_PATH}} \
          -binary-path={{.SERVER_BIN_PATH}} \
          -database-dsn={{.DATABASE_DSN}} \
          -server-port=$SERVER_PORT \
          -source-path=.

  iter-11:
    deps: [ unit-tests, iter-10, ]
    vars:
      DATABASE_DSN: postgres://postgres:password@localhost:5432/postgres
    preconditions:
      - test -n "$(lsof -i :5432)"
    cmds:
      - |
        SERVER_PORT=$(random-practicum unused-port)
        ADDRESS="localhost:${SERVER_PORT}"
        TEMP_FILE=$(random-practicum tempfile)
        metricstest -test.v -test.run=^TestIteration11$ \
          -agent-binary-path={{.AGENT_BIN_PATH}} \
          -binary-path={{.SERVER_BIN_PATH}} \
          -database-dsn={{.DATABASE_DSN}} \
          -server-port=$SERVER_PORT \
          -source-path=.

  iter-12:
    deps: [ unit-tests, iter-11, ]
    vars:
      DATABASE_DSN: postgres://postgres:password@localhost:5432/postgres
    preconditions:
      - test -n "$(lsof -i :5432)"
    cmds:
      - |
        SERVER_PORT=$(random-practicum unused-port)
        ADDRESS="localhost:${SERVER_PORT}"
        TEMP_FILE=$(random-practicum tempfile)
        metricstest -test.v -test.run=^TestIteration12$ \
          -agent-binary-path={{.AGENT_BIN_PATH}} \
          -binary-path={{.SERVER_BIN_PATH}} \
          -database-dsn={{.DATABASE_DSN}} \
          -server-port=$SERVER_PORT \
          -source-path=.

  iter-13:
    deps: [ unit-tests, iter-12, ]
    vars:
      DATABASE_DSN: postgres://postgres:password@localhost:5432/postgres
    preconditions:
      - test -n "$(lsof -i :5432)"
    cmds:
      - |
        SERVER_PORT=$(random-practicum unused-port)
        ADDRESS="localhost:${SERVER_PORT}"
        TEMP_FILE=$(random-practicum tempfile)
        metricstest -test.v -test.run=^TestIteration13$ \
          -agent-binary-path={{.AGENT_BIN_PATH}} \
          -binary-path={{.SERVER_BIN_PATH}} \
          -database-dsn={{.DATABASE_DSN}} \
          -server-port=$SERVER_PORT \
          -source-path=.

  iter-14:
    deps: [ unit-tests, iter-13 ]
    vars:
      DATABASE_DSN: postgres://postgres:password@localhost:5432/postgres
    preconditions:
      - test -n "$(lsof -i :5432)"
    cmds:
      - |
        SERVER_PORT=$(random-practicum unused-port)
        ADDRESS="localhost:${SERVER_PORT}"
        TEMP_FILE=$(random-practicum tempfile)
        metricstest -test.v -test.run=^TestIteration14$ \
          -agent-binary-path={{.AGENT_BIN_PATH}} \
          -binary-path={{.SERVER_BIN_PATH}} \
          -database-dsn={{.DATABASE_DSN}} \
          -key=$TEMP_FILE \
          -server-port=$SERVER_PORT \
          -source-path=.

  iter-14-race:
    deps: [ unit-tests, iter-14 ]
    cmds:
      - go test -v -count 1 -race ./...
