version: '3'

env:

  TASK_X_MAP_VARIABLES: 1

  BRANCH_NUMBER:
    sh: git branch --show-current | grep -o '[0-9]\+'

  AGENT_BIN_DIR: cmd/agent
  AGENT_BIN_NAME: agent
  AGENT_BIN_PATH: "{{.AGENT_BIN_DIR}}/{{.AGENT_BIN_NAME}}"

  SERVER_BIN_DIR: cmd/server
  SERVER_BIN_NAME: server
  SERVER_BIN_PATH: "{{.SERVER_BIN_DIR}}/{{.SERVER_BIN_NAME}}"
  SERVER_PORT: 8888
  SERVER_STORAGE_FILE_PATH: "metrics.backup.txt"

tasks:

  build-server:
    cmds:
      - go build -v -o "{{.SERVER_BIN_PATH}}" "{{.SERVER_BIN_DIR}}/main.go"

  build-agent:
    cmds:
      - go build -v -o "{{.AGENT_BIN_PATH}}" "{{.AGENT_BIN_DIR}}/main.go"

  build:
    cmds:
      - task: build-agent
      - task: build-server

  run-server:
    deps: [ build-server ]
    cmds:
      - "{{.SERVER_BIN_PATH}} {{.CLI_ARGS}}"

  run-agent:
    deps: [ build-agent ]
    cmds:
      - "{{.AGENT_BIN_PATH}} {{.CLI_ARGS}}"

  linter:
    cmd: go vet -vettool=`which statictest` ./...

  unit-tests:
    vars:
      CACHED: '{{.CACHED | default "-count 1" }}'
    cmds:
      - go test {{.CACHED}}  ./...

  tests:
    deps: [ linter, build ]
    cmds:
      - task: unit-tests
      - >-
        metricstest
        -test.v
        -source-path=.
        -binary-path="{{.SERVER_BIN_PATH}}"
        -server-port="{{.SERVER_PORT}}"
        -agent-binary-path="{{.AGENT_BIN_PATH}}"
        -test.run="^TestIteration([1-{{.BRANCH_NUMBER}}]|[1-{{.BRANCH_NUMBER}}][A-Z])$"
        -file-storage-path={{.SERVER_STORAGE_FILE_PATH}}

  test-iter-*:
    deps: [ linter, build ]
    vars:
      ITER: '{{index .MATCH 0}}'
    cmds:
      - task: unit-tests
      - >-
        metricstest
        -test.v
        -source-path=.
        -binary-path="{{.SERVER_BIN_PATH}}"
        -server-port="{{.SERVER_PORT}}"
        -agent-binary-path="{{.AGENT_BIN_PATH}}"
        -test.run="^TestIteration{{.ITER}}"
        -file-storage-path={{.SERVER_STORAGE_FILE_PATH}}
